// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9uZ-bYUX1F4Nq5YiVr6sj649ie-LFpi8',
    appId: '1:102022933723:web:d2b33a590f284ca073b0fe',
    messagingSenderId: '102022933723',
    projectId: 'notifyapp-f532b',
    authDomain: 'notifyapp-f532b.firebaseapp.com',
    storageBucket: 'notifyapp-f532b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wvD85KW9vLQNJnGrmXpo4VO01W5lTdo',
    appId: '1:102022933723:android:70d02be7dab1411973b0fe',
    messagingSenderId: '102022933723',
    projectId: 'notifyapp-f532b',
    storageBucket: 'notifyapp-f532b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKj2Ng2gCrTbNNGM1BWTnRUteSUCrHdSY',
    appId: '1:102022933723:ios:003debdb89bbdabd73b0fe',
    messagingSenderId: '102022933723',
    projectId: 'notifyapp-f532b',
    storageBucket: 'notifyapp-f532b.firebasestorage.app',
    iosBundleId: 'com.example.notifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKj2Ng2gCrTbNNGM1BWTnRUteSUCrHdSY',
    appId: '1:102022933723:ios:003debdb89bbdabd73b0fe',
    messagingSenderId: '102022933723',
    projectId: 'notifyapp-f532b',
    storageBucket: 'notifyapp-f532b.firebasestorage.app',
    iosBundleId: 'com.example.notifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9uZ-bYUX1F4Nq5YiVr6sj649ie-LFpi8',
    appId: '1:102022933723:web:29e95e92c35ab2fd73b0fe',
    messagingSenderId: '102022933723',
    projectId: 'notifyapp-f532b',
    authDomain: 'notifyapp-f532b.firebaseapp.com',
    storageBucket: 'notifyapp-f532b.firebasestorage.app',
  );
}
